import { describe, expect, it } from "vitest";

import { isSafeMediaFilename, sniffImage } from "./media-sniff.js";

function pad(header: number[], size = 64): Buffer {
  return Buffer.concat([Buffer.from(header), Buffer.alloc(Math.max(0, size - header.length))]);
}

const PNG = (() => {
  const b = pad([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]);
  b.writeUInt32BE(1200, 16);
  b.writeUInt32BE(630, 20);
  return b;
})();

const GIF = (() => {
  const b = pad([...Buffer.from("GIF89a", "ascii")]);
  b.writeUInt16LE(320, 6);
  b.writeUInt16LE(240, 8);
  return b;
})();

const JPEG = (() => {
  // SOI (FFD8), then SOF0 at offset 2. Its payload is
  // [length(2), precision(1), height(2), width(2), ...] — so height lands at
  // index 7 and width at index 9.
  const b = pad([0xff, 0xd8, 0xff, 0xc0, 0x00, 0x11, 0x08]);
  b.writeUInt16BE(480, 7); // height
  b.writeUInt16BE(640, 9); // width
  return b;
})();

const WEBP_VP8L = (() => {
  const b = pad([...Buffer.from("RIFF", "ascii"), 0, 0, 0, 0, ...Buffer.from("WEBPVP8L", "ascii")]);
  // 14 bits width-1, then 14 bits height-1.
  b.writeUInt32LE((99 & 0x3fff) | ((49 & 0x3fff) << 14), 21);
  return b;
})();

const AVIF = pad([0, 0, 0, 0, ...Buffer.from("ftypavif", "ascii")]);

describe("sniffImage", () => {
  it("identifies PNG and reads its dimensions", () => {
    expect(sniffImage(PNG)).toEqual({ mime: "image/png", ext: "png", width: 1200, height: 630 });
  });

  it("identifies GIF and reads its dimensions", () => {
    expect(sniffImage(GIF)).toEqual({ mime: "image/gif", ext: "gif", width: 320, height: 240 });
  });

  it("identifies JPEG and reads its dimensions from the frame header", () => {
    expect(sniffImage(JPEG)).toEqual({ mime: "image/jpeg", ext: "jpg", width: 640, height: 480 });
  });

  it("identifies lossless WebP and reads its dimensions", () => {
    expect(sniffImage(WEBP_VP8L)).toEqual({
      mime: "image/webp",
      ext: "webp",
      width: 100,
      height: 50,
    });
  });

  it("identifies AVIF, leaving dimensions unknown", () => {
    expect(sniffImage(AVIF)).toEqual({ mime: "image/avif", ext: "avif", width: null, height: null });
  });

  /**
   * The upload path ignores the declared MIME type and the filename entirely.
   * This is the check that stops a shell script arriving as "photo.png".
   */
  it("rejects a shell script named like an image", () => {
    expect(sniffImage(pad([...Buffer.from("#!/bin/sh\necho hi\n", "ascii")]))).toBeNull();
  });

  /** SVG is deliberately unsupported: it can carry script on our own origin. */
  it("rejects SVG", () => {
    expect(sniffImage(pad([...Buffer.from('<svg xmlns="http://www.w3.org/2000/svg">', "ascii")]))).toBeNull();
  });

  it("rejects HTML, PDF and empty input", () => {
    expect(sniffImage(pad([...Buffer.from("<!doctype html>", "ascii")]))).toBeNull();
    expect(sniffImage(pad([...Buffer.from("%PDF-1.7", "ascii")]))).toBeNull();
    expect(sniffImage(Buffer.alloc(0))).toBeNull();
    expect(sniffImage(Buffer.alloc(8))).toBeNull();
  });

  /** A real PNG header with a swapped byte must not be accepted as "close enough". */
  it("rejects a near-miss signature", () => {
    const broken = Buffer.from(PNG);
    broken[3] = 0x00;
    expect(sniffImage(broken)).toBeNull();
  });
});

describe("isSafeMediaFilename", () => {
  it("accepts the stored uuid form", () => {
    expect(isSafeMediaFilename("3f2504e0-4f89-41d3-9a0c-0305e82c3301.png")).toBe(true);
    expect(isSafeMediaFilename("3f2504e0-4f89-41d3-9a0c-0305e82c3301-640w.webp")).toBe(true);
  });

  it("rejects traversal and anything not generated by us", () => {
    for (const name of [
      "../../etc/passwd",
      "..%2f..%2fetc%2fpasswd",
      "/etc/passwd",
      "photo.png",
      "3f2504e0-4f89-41d3-9a0c-0305e82c3301.svg",
      "3f2504e0-4f89-41d3-9a0c-0305e82c3301.png/../x",
      "3f2504e0-4f89-41d3-9a0c-0305e82c3301.php",
      "",
    ]) {
      expect(isSafeMediaFilename(name), name).toBe(false);
    }
  });
});
