import AxeBuilder from "@axe-core/playwright";
import type { Page, Route } from "@playwright/test";

import { expect, interactive, test } from "./fixtures";

/**
 * The About terminal as the portfolio assistant. The API is cross-origin in
 * the build (`VITE_API_BASE_URL`), so its answers are mocked here with CORS
 * and a preflight, as an AI SDK UI message stream (server-sent events).
 */

const cors = {
  "access-control-allow-origin": "*",
  "access-control-allow-headers": "content-type",
  "access-control-allow-methods": "GET, POST",
};

type Chunk = Record<string, unknown>;

function stream(chunks: Chunk[]): string {
  return [...chunks.map((c) => `data: ${JSON.stringify(c)}\n\n`), "data: [DONE]\n\n"].join("");
}

function answer(options: {
  id?: string;
  text: string;
  tools?: Chunk[];
  sources?: Chunk[];
  followups?: string[];
}): Chunk[] {
  const id = options.id ?? "m_e2e00000001";
  return [
    { type: "start", messageId: id, messageMetadata: { createdAt: Date.now() } },
    { type: "start-step" },
    ...(options.tools ?? []),
    ...(options.sources ?? []),
    { type: "text-start", id: "t1" },
    ...options.text.split(/(?<= )/).map((delta) => ({ type: "text-delta", id: "t1", delta })),
    { type: "text-end", id: "t1" },
    ...(options.followups
      ? [
          { type: "tool-input-start", toolCallId: "f1", toolName: "suggest_followups" },
          {
            type: "tool-input-available",
            toolCallId: "f1",
            toolName: "suggest_followups",
            input: { items: options.followups },
          },
          { type: "tool-output-available", toolCallId: "f1", output: { ok: true } },
        ]
      : []),
    { type: "finish-step" },
    {
      type: "finish",
      finishReason: "stop",
      messageMetadata: {
        sig: "signed",
        model: "gemini-3.5-flash-lite",
        fallback: false,
        route: "lite",
        totalMs: 1300,
        tokens: { input: 10_000, cached: 9_100, output: 60 },
      },
    },
  ];
}

const SEARCH_STEP: Chunk[] = [
  { type: "tool-input-start", toolCallId: "s1", toolName: "search_portfolio" },
  {
    type: "tool-input-available",
    toolCallId: "s1",
    toolName: "search_portfolio",
    input: { query: "evals" },
  },
  { type: "tool-output-available", toolCallId: "s1", output: { results: [] } },
];

interface AskMock {
  bodies: { sessionId: string; locale: string; messages: { role: string }[] }[];
}

async function mockAsk(
  page: Page,
  respond: (route: Route, n: number) => Promise<void> | void,
  config: Record<string, unknown> = {},
): Promise<AskMock> {
  const mock: AskMock = { bodies: [] };
  await page.route("**/v1/ask/config", (route) =>
    route.fulfill({
      headers: cors,
      json: {
        state: "ok",
        deep: true,
        suggestions: { en: [], de: [] },
        limits: { maxChars: 600, historyTurns: 8 },
        model: "gemini-3.5-flash-lite",
        ...config,
      },
    }),
  );
  await page.route("**/v1/ask", async (route) => {
    if (route.request().method() === "OPTIONS") {
      await route.fulfill({ status: 204, headers: cors });
      return;
    }
    mock.bodies.push(route.request().postDataJSON());
    await respond(route, mock.bodies.length);
  });
  return mock;
}

function sse(route: Route, chunks: Chunk[]) {
  return route.fulfill({
    status: 200,
    headers: {
      ...cors,
      "content-type": "text/event-stream",
      "x-vercel-ai-ui-message-stream": "v1",
    },
    body: stream(chunks),
  });
}

/** The About section's prompt, once its code has loaded. */
async function openPrompt(page: Page, path = "/en") {
  await page.goto(path);
  await interactive(page);
  await page.locator("#about").scrollIntoViewIfNeeded();
  const prompt = page.locator("#about textarea");
  await expect(prompt).toBeVisible();
  return prompt;
}

async function run(prompt: ReturnType<Page["locator"]>, text: string) {
  await prompt.fill(text);
  await prompt.press("Enter");
}

test.use({ reducedMotion: "reduce" });

test.describe("assistant terminal", () => {
  test("the intro, prompt and AI disclosure are in the server-rendered page", async ({
    request,
  }) => {
    const html = await (await request.get("/en")).text();
    expect(html).toContain("cat philosophy.txt");
    expect(html).toContain('type a question, or "help"');
    expect(html).toContain("Answers are generated by an AI from the content of this site.");
    // The shell itself (and the AI SDK) loads in the browser only.
    expect(html).not.toContain('id="ask-input');
  });

  test("shell commands answer locally, with history and Tab completion", async ({ page }) => {
    const mock = await mockAsk(page, () => undefined);
    const prompt = await openPrompt(page);
    const log = page.locator("#about [role=log]");

    await run(prompt, "help");
    await expect(log).toContainText("ls projects");
    await expect(log).toContainText("Anything else is a question for the AI assistant.");

    await run(prompt, "ls projects");
    await expect(log).toContainText("project-one");

    await prompt.fill("cat project-o");
    await prompt.press("Tab");
    await expect(prompt).toHaveValue("cat project-one");
    await prompt.press("Enter");
    await expect(log.getByRole("link", { name: "case study" })).toHaveAttribute(
      "href",
      "/en/work/project-one",
    );

    await prompt.press("ArrowUp");
    await expect(prompt).toHaveValue("cat project-one");
    await prompt.press("ArrowUp");
    await expect(prompt).toHaveValue("ls projects");

    await prompt.fill("");
    await prompt.press("Control+l");
    await expect(log).not.toContainText("project-one");
    expect(mock.bodies).toHaveLength(0);
  });

  test("a question streams an answer with its tool step, footnote, follow-ups and stats", async ({
    page,
    problems,
  }) => {
    const mock = await mockAsk(page, (route) =>
      sse(
        route,
        answer({
          text: "He runs **evals** before every prompt change [^project:project-one@en].",
          tools: SEARCH_STEP,
          sources: [
            {
              type: "source-url",
              sourceId: "project:project-one@en",
              url: "/en/work/project-one",
              title: "Project one",
            },
          ],
          followups: ["Which stack did he use?"],
        }),
      ),
    );
    const prompt = await openPrompt(page);
    await run(prompt, "stats");
    await run(prompt, "How does he test prompts?");

    const log = page.locator("#about [role=log]");
    await expect(log).toContainText("He runs evals before every prompt change");
    await expect(log).toContainText('› search "evals"');
    const cite = log.getByRole("link", { name: /sources 1: Project one/ });
    await expect(cite).toHaveAttribute("href", "/en/work/project-one");
    await expect(log.getByRole("link", { name: "Project one", exact: true })).toBeVisible();
    await expect(log).toContainText("gemini-3.5-flash-lite · 1.3 s · 91% cached");
    // Announced once, in full, without markup or markers.
    await expect(page.locator("#about [aria-live=polite]")).toHaveText(
      "He runs evals before every prompt change.",
    );

    const body = mock.bodies[0]!;
    expect(body.locale).toBe("en");
    expect(body.sessionId).toMatch(/^[A-Za-z0-9_-]{16,64}$/);
    expect(body.messages.map((m) => m.role)).toEqual(["user"]);

    // A follow-up is one click, and carries the signed answer as history.
    await log.getByRole("button", { name: "Which stack did he use?" }).click();
    await expect.poll(() => mock.bodies.length).toBe(2);
    expect(mock.bodies[1]!.messages.map((m) => m.role)).toEqual(["user", "assistant", "user"]);
    expect(problems.cspViolations).toEqual([]);
    expect(problems.pageErrors).toEqual([]);
  });

  test("an answer shows while it is still streaming", async ({ page }) => {
    // A mocked route delivers its body at once, which hid a bug: the answer
    // showed only after a reload. Here the stream pauses mid-answer, as a
    // model does, and the words so far must already be on screen.
    const chunks = answer({ text: "First words arrive now, the rest a little later." });
    const cut = chunks.findIndex((c) => c["type"] === "text-delta" && c["delta"] === "now, ");
    await page.addInitScript(
      ({ head, tail }) => {
        const original = window.fetch.bind(window);
        window.fetch = async (input, init) => {
          const url =
            typeof input === "string" ? input : input instanceof URL ? input.href : input.url;
          if (!url.endsWith("/v1/ask") || init?.method !== "POST") return original(input, init);
          const encoder = new TextEncoder();
          const wait = (ms: number) => new Promise((resolve) => setTimeout(resolve, ms));
          const body = new ReadableStream<Uint8Array>({
            async start(controller) {
              const send = (chunk: unknown) =>
                controller.enqueue(encoder.encode(`data: ${JSON.stringify(chunk)}\n\n`));
              for (const chunk of head) {
                send(chunk);
                await wait(50);
              }
              await wait(3000);
              for (const chunk of tail) send(chunk);
              controller.enqueue(encoder.encode("data: [DONE]\n\n"));
              controller.close();
            },
          });
          return new Response(body, {
            headers: { "content-type": "text/event-stream", "x-vercel-ai-ui-message-stream": "v1" },
          });
        };
      },
      { head: chunks.slice(0, cut + 1), tail: chunks.slice(cut + 1) },
    );
    await mockAsk(page, () => undefined);
    const prompt = await openPrompt(page);
    await run(prompt, "What is he doing?");

    const log = page.locator("#about [role=log]");
    await expect(log).toContainText("First words arrive now,", { timeout: 2500 });
    await expect(log).not.toContainText("a little later");
    await expect(log).toContainText("First words arrive now, the rest a little later.");
  });

  test("German pages ask in German", async ({ page }) => {
    const mock = await mockAsk(page, (route) =>
      sse(route, answer({ text: "Er testet jede Änderung." })),
    );
    const prompt = await openPrompt(page, "/de");
    await run(prompt, "Wie testet er?");
    await expect(page.locator("#about [role=log]")).toContainText("Er testet jede Änderung.");
    expect(mock.bodies[0]!.locale).toBe("de");
  });

  test("a rate limit shows a countdown, and a failed answer can be retried", async ({ page }) => {
    await mockAsk(page, async (route, n) => {
      if (n === 1) {
        await route.fulfill({
          status: 429,
          headers: cors,
          json: { error: "rate_limited", retryAfter: 42 },
        });
      } else if (n === 2) {
        await sse(route, [
          { type: "start", messageId: "m_e2e00000002" },
          { type: "error", errorText: "timeout" },
        ]);
      } else {
        await sse(route, answer({ id: "m_e2e00000003", text: "Second try worked." }));
      }
    });
    const prompt = await openPrompt(page);
    const log = page.locator("#about [role=log]");

    await run(prompt, "First question");
    await expect(log).toContainText(/try again in 4[0-2]s/);

    // Past the limit (the mock does not enforce it; the terminal does).
    await page.evaluate(() => sessionStorage.clear());
    await page.reload();
    const again = await openPrompt(page, page.url());
    await run(again, "Second question");
    await expect(log).toContainText("That took too long to answer.");
    await log.getByRole("button", { name: /retry/ }).click();
    await expect(log).toContainText("Second try worked.");
  });

  test("a resting assistant answers from the offline shell and offers contact", async ({
    page,
  }) => {
    const mock = await mockAsk(page, () => undefined, { state: "resting" });
    const prompt = await openPrompt(page);
    await run(prompt, "Which projects has he built?");
    const log = page.locator("#about [role=log]");
    await expect(log).toContainText("The assistant is resting.");
    await expect(log).toContainText("project-one");
    await expect(log).toContainText("type `contact`");
    expect(mock.bodies).toHaveLength(0);
  });

  test("the hand-off to the contact form waits for the visitor's yes", async ({ page }) => {
    const summary = "Wants to discuss a six-month contract for an AI platform.";
    await mockAsk(page, (route) =>
      sse(route, [
        ...answer({ text: "Happy to help you reach him." }).slice(0, -2),
        { type: "tool-input-start", toolCallId: "h1", toolName: "handoff_contact" },
        {
          type: "tool-input-available",
          toolCallId: "h1",
          toolName: "handoff_contact",
          input: { summary },
        },
        {
          type: "tool-output-available",
          toolCallId: "h1",
          output: { ok: true, awaitingConfirmation: true },
        },
        { type: "finish-step" },
        {
          type: "finish",
          finishReason: "tool-calls",
          messageMetadata: { sig: "s", model: "gemini-3.5-flash-lite" },
        },
      ]),
    );
    const prompt = await openPrompt(page);
    await run(prompt, "I want to hire him");
    const confirm = page.getByRole("group", {
      name: "Hand this conversation to the contact form?",
    });
    await expect(confirm).toBeVisible();
    await expect(page.locator("#contact-message")).toHaveValue("");

    await confirm.getByRole("button", { name: "yes" }).click();
    await expect(page.locator("#contact-message")).toHaveValue(summary);
    await expect(page.locator("#contact-name")).toBeFocused();
  });

  test("“ask my portfolio” in the hero goes to the prompt and focuses it", async ({ page }) => {
    await mockAsk(page, () => undefined);
    await page.goto("/en");
    await interactive(page);
    await page.getByRole("link", { name: "ask my portfolio" }).click();
    await expect(page.locator("#about textarea")).toBeFocused();
  });

  test("other pages open the same assistant in a sheet", async ({ page }) => {
    await mockAsk(page, (route) => sse(route, answer({ text: "From the sheet." })));
    await page.goto("/en/work/project-one");
    await interactive(page);
    await page.getByRole("button", { name: "ask my portfolio" }).click();
    const sheet = page.getByRole("dialog", { name: "ask my portfolio" });
    const prompt = sheet.locator("textarea");
    await expect(prompt).toBeFocused();
    await run(prompt, "Hello");
    await expect(sheet).toContainText("From the sheet.");
    await page.keyboard.press("Escape");
    await expect(sheet).toBeHidden();
  });
});

async function axeViolations(page: Page) {
  const { violations } = await new AxeBuilder({ page })
    .withTags(["wcag2a", "wcag2aa", "wcag21a", "wcag21aa", "wcag22aa", "best-practice"])
    .analyze();
  return violations.map((v) => ({
    rule: v.id,
    help: v.help,
    targets: v.nodes.slice(0, 5).map((n) => n.target.join(" ")),
  }));
}

// The terminal's states appear only after typing, which the page-level axe runs never do.
for (const colorScheme of ["dark", "light"] as const) {
  test.describe(`assistant accessibility (${colorScheme})`, () => {
    test.use({ colorScheme });

    test("an answer, its footnotes, follow-ups, feedback and a hand-off prompt", async ({
      page,
    }) => {
      await mockAsk(page, (route) =>
        sse(route, [
          ...answer({
            text: "He runs **evals** first [^project:project-one@en].",
            tools: SEARCH_STEP,
            sources: [
              {
                type: "source-url",
                sourceId: "project:project-one@en",
                url: "/en/work/project-one",
                title: "Project one",
              },
            ],
            followups: ["Which stack?"],
          }).slice(0, -2),
          { type: "tool-input-start", toolCallId: "h1", toolName: "handoff_contact" },
          {
            type: "tool-input-available",
            toolCallId: "h1",
            toolName: "handoff_contact",
            input: { summary: "Hiring enquiry." },
          },
          { type: "tool-output-available", toolCallId: "h1", output: { ok: true } },
          { type: "finish-step" },
          {
            type: "finish",
            finishReason: "tool-calls",
            messageMetadata: { sig: "s", model: "gemini-3.5-flash-lite" },
          },
        ]),
      );
      const prompt = await openPrompt(page);
      await run(prompt, "help");
      await run(prompt, "stats");
      await run(prompt, "How does he test?");
      await expect(page.getByRole("group", { name: /Hand this conversation/ })).toBeVisible();
      expect(await axeViolations(page)).toEqual([]);
    });

    test("the sheet on another page", async ({ page }) => {
      await mockAsk(page, (route) => sse(route, answer({ text: "From the sheet." })));
      await page.goto("/en/work/project-one");
      await interactive(page);
      await page.getByRole("button", { name: "ask my portfolio" }).click();
      const sheet = page.getByRole("dialog", { name: "ask my portfolio" });
      await run(sheet.locator("textarea"), "Hello");
      await expect(sheet).toContainText("From the sheet.");
      expect(await axeViolations(page)).toEqual([]);
    });
  });
}

test.describe("assistant on a phone", () => {
  test.use({ viewport: { width: 390, height: 780 }, hasTouch: true, isMobile: true });

  test("focusing the prompt opens the terminal full screen; Esc closes it", async ({ page }) => {
    await mockAsk(page, () => undefined);
    const prompt = await openPrompt(page);
    await prompt.focus();
    const frame = page.locator("#about .ask-expanded");
    await expect(frame).toBeVisible();
    const box = await frame.boundingBox();
    expect(box?.width).toBeGreaterThanOrEqual(389);
    await expect(prompt).toBeFocused();
    await page.keyboard.press("Escape");
    await expect(frame).toHaveCount(0);
  });
});
