import type { Locale } from "../content/schema.js";

/**
 * Which language a visitor writes in: the answer follows it, not the page. A
 * count of common words tells German from English even in a three-word
 * question. Words both languages use ("was", "an", "also", "will") count for
 * neither, and neither do the tech terms German borrows ("Backend", "Stack",
 * "Skills"), so "Was ist sein Backend-Stack?" still reads as German.
 */

const GERMAN_WORDS = new Set([
  "und",
  "oder",
  "aber",
  "der",
  "die",
  "das",
  "den",
  "dem",
  "des",
  "ein",
  "eine",
  "einen",
  "einem",
  "einer",
  "eines",
  "ist",
  "sind",
  "war",
  "hat",
  "hatte",
  "haben",
  "wird",
  "wurde",
  "werden",
  "kann",
  "gibt",
  "nicht",
  "kein",
  "keine",
  "mit",
  "für",
  "auf",
  "bei",
  "von",
  "vom",
  "zum",
  "zur",
  "zu",
  "im",
  "über",
  "nach",
  "aus",
  "auch",
  "noch",
  "schon",
  "nur",
  "sich",
  "er",
  "ihm",
  "ihn",
  "sein",
  "seine",
  "seinem",
  "seinen",
  "seiner",
  "seines",
  "ich",
  "du",
  "mir",
  "mich",
  "dir",
  "wir",
  "uns",
  "wer",
  "wie",
  "wo",
  "woher",
  "warum",
  "wieso",
  "weshalb",
  "welche",
  "welcher",
  "welches",
  "welchen",
  "wann",
  "womit",
  "woran",
  "bitte",
  "danke",
  "hallo",
  "macht",
  "gemacht",
  "arbeitet",
  "gearbeitet",
  "erzähl",
  "erzähle",
  "lebt",
  "wohnt",
  "spricht",
  "sprachen",
  "projekt",
  "projekte",
  "erfahrung",
  "kenntnisse",
  "lebenslauf",
  "deutschland",
  "verwendet",
  "entwickelt",
  "gebaut",
  "standort",
  "verfügbar",
  "verfügbarkeit",
]);

const ENGLISH_WORDS = new Set([
  "the",
  "and",
  "or",
  "but",
  "is",
  "are",
  "were",
  "be",
  "been",
  "has",
  "have",
  "had",
  "does",
  "do",
  "did",
  "can",
  "could",
  "would",
  "should",
  "not",
  "with",
  "for",
  "of",
  "to",
  "from",
  "by",
  "about",
  "at",
  "he",
  "his",
  "him",
  "this",
  "that",
  "there",
  "what",
  "who",
  "how",
  "where",
  "why",
  "which",
  "when",
  "tell",
  "you",
  "your",
  "my",
  "please",
  "thanks",
  "thank",
  "lives",
  "works",
  "worked",
  "uses",
  "used",
  "includes",
  "built",
  "projects",
  "experience",
  "speak",
  "speaks",
  "languages",
  "hire",
  "available",
]);

export function detectLanguage(text: string): Locale | null {
  let de = 0;
  let en = 0;
  for (const word of text.toLowerCase().match(/\p{L}+/gu) ?? []) {
    if (GERMAN_WORDS.has(word) || /[äöüß]/.test(word)) de++;
    if (ENGLISH_WORDS.has(word)) en++;
  }
  if (de === en) return null;
  return de > en ? "de" : "en";
}

/**
 * The newest visitor message with a clear language decides, so a lone
 * "Borealis?" after a German question is answered in German. Null when none
 * has one: a name alone, or a language that is neither.
 */
export function visitorLanguage(texts: readonly string[]): Locale | null {
  for (let i = texts.length - 1; i >= 0; i--) {
    const language = detectLanguage(texts[i]!);
    if (language) return language;
  }
  return null;
}
